"""Generates the Stage 1 raw-inference corpus (doc/benchmark.md §9 Stage 1).

Four synthetic documents under `fixtures/prompts/`: `{8k,16k}_{primary,alternate}.txt`.
Unlike `build_workspace.py`/`build_testrepo.py`, nothing here is graded — Stage 1
measures throughput and latency, not correctness — so there are no
`fixtures/expected/` entries to emit.

Sizing is a 4-characters-per-token heuristic, used only to decide how much
filler text to generate. Actual token counts differ by tokeniser and are
recorded from the API response, never assumed equal to the target (§9 Stage 1).
"""

from __future__ import annotations

import random
from pathlib import Path

OUT = Path(__file__).resolve().parent / "prompts"

CHARS_PER_TOKEN = 4
TARGET_TOKENS = {"8k": 8192, "16k": 16384}

SEEDS = {
    ("8k", "primary"): 20260201,
    ("8k", "alternate"): 20260202,
    ("16k", "primary"): 20260203,
    ("16k", "alternate"): 20260204,
}

TEAMS = [
    "Platform", "Search", "Billing", "Notifications", "Data Pipeline",
    "Identity", "Mobile", "Observability", "Storage", "Edge",
]

WORKSTREAMS = [
    "the migration to the new queueing backend",
    "the rollout of tiered rate limiting",
    "the deprecation of the legacy export format",
    "the consolidation of duplicate metrics pipelines",
    "the rewrite of the retry-and-backoff layer",
    "the audit of stale feature flags",
    "the move to structured logging",
    "the redesign of the on-call escalation path",
    "the removal of the deprecated authentication shim",
    "the standardisation of internal error codes",
]

FINDINGS = [
    "Latency at the 99th percentile improved after the change, but the median was unaffected.",
    "A small fraction of requests began retrying more aggressively than intended.",
    "The change reduced memory pressure on the affected hosts by a noticeable margin.",
    "No regression was observed in the downstream consumers during the rollout window.",
    "One dependency had not been updated to the new interface and required a follow-up patch.",
    "The rollout was paused partway through after an unrelated alert fired in the same window.",
    "Throughput held steady under the increased load generated by the new test suite.",
    "A configuration default diverged between environments and was corrected during review.",
    "The dashboard used to track this metric was itself found to be double-counting events.",
    "Rollback was not required; the change proceeded to full deployment on schedule.",
]

RISKS = [
    "the remaining hosts on the old configuration, which must be migrated before the next release",
    "a dependency on a library whose maintenance status is unclear",
    "the absence of an automated rollback path for this component",
    "a manual step in the deployment process that has caused delays twice before",
    "test coverage that does not yet exercise the failure path directly",
    "a shared resource whose capacity has not been re-evaluated since the last redesign",
]

ACTIONS = [
    "file a follow-up ticket and assign an owner before the next planning cycle",
    "schedule a review with the team most affected by the change",
    "add a regression test that would have caught this earlier",
    "update the runbook to reflect the new behaviour",
    "confirm the change with the on-call rotation before the next deploy window",
    "circulate a short write-up once the remaining work is done",
]

CLOSINGS = {
    "primary": (
        "\n\n---\n\nWrite a detailed, section-by-section summary of the report above. "
        "Cover every team's update in order, using complete sentences, and note any "
        "risks or follow-up actions you find. Aim for at least 400 words.\n"
    ),
    "alternate": (
        "\n\n---\n\nWrite an exhaustive summary of the report above, at least 600 words, "
        "covering every section in full detail with no section omitted. Include every "
        "risk and every follow-up action by name.\n"
    ),
}


def _section(team: str, rng: random.Random) -> str:
    lines = [f"## {team}", ""]
    lines.append(f"Update on {rng.choice(WORKSTREAMS)}.")
    lines.append("")
    for finding in rng.sample(FINDINGS, 3):
        lines.append(f"- {finding}")
    lines.append("")
    lines.append(f"Open risk: {rng.choice(RISKS)}.")
    lines.append(f"Next step: {rng.choice(ACTIONS)}.")
    lines.append("")
    return "\n".join(lines)


def build_document(tier: str, variant: str) -> str:
    rng = random.Random(SEEDS[(tier, variant)])
    target_chars = TARGET_TOKENS[tier] * CHARS_PER_TOKEN

    header = (
        "# Quarterly Engineering Status Report\n\n"
        "This report collects per-team updates for the current quarter. Each section "
        "below covers one team: what changed, what was found, and what remains open.\n\n"
    )

    body_parts = [header]
    length = len(header)
    while length < target_chars:
        team = rng.choice(TEAMS)
        section = _section(team, rng)
        body_parts.append(section)
        length += len(section)

    return "".join(body_parts) + CLOSINGS[variant]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for tier in TARGET_TOKENS:
        for variant in ("primary", "alternate"):
            text = build_document(tier, variant)
            path = OUT / f"{tier}_{variant}.txt"
            path.write_text(text, encoding="utf-8")
            print(f"{path.name}: {len(text)} chars (~{len(text) // CHARS_PER_TOKEN} tokens by heuristic)")


if __name__ == "__main__":
    main()
